[server]

# List of folders that should not be watched for changes. This impacts both "Run on Save" and @st.cache.
# Relative paths will be taken as relative to the current working directory.
# Example: ['/home/user1/env', 'relative/path/to/folder']
# Default: []
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
folderWatchBlacklist = []

maxMessageSize = 2000

# Change the type of file watcher used by Streamlit, or turn it off completely.
# Allowed values: * "auto" : Streamlit will attempt to use the watchdog module, and falls back to polling if watchdog is not available. * "watchdog" : Force Streamlit to use the watchdog module. * "poll" : Force Streamlit to always use polling. * "none" : Streamlit will not watch files.
# Default: "auto"
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas, this should be set to the same value across all replicas to ensure they all share the same secret.
# Default: randomly generated secret key.
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
cookieSecret = "2c414c16ac4fd30c17ae02fb65126628e9b4718a4332c994239eab21b182b1b9"

# If false, will attempt to open a browser window on start.
# Default: false unless (1) we are on a Linux box where DISPLAY is unset, or (2) server.liveSave is set.
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
headless = false

# Automatically rerun script when the file is modified on disk.
# Default: false
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
runOnSave = false

# The address where the server will listen for client and browser connections. Use this if you want to bind the server to a specific address. If set, the server will only be accessible from this address, and not from any aliases (like localhost).
# Default: (unset)
#address =

# The port where the server will listen for browser connections.
# Default: 8501
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
port = 8501

# The base path for the URL where Streamlit should be served from.
# Default: ""
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
baseUrlPath = ""

# Enables support for Cross-Origin Request Sharing (CORS) protection, for added security.
# Due to conflicts between CORS and XSRF, if `server.enableXsrfProtection` is on and `server.enableCORS` is off at the same time, we will prioritize `server.enableXsrfProtection`.
# Default: true
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
enableCORS = true

# Enables support for Cross-Site Request Forgery (XSRF) protection, for added security.
# Due to conflicts between CORS and XSRF, if `server.enableXsrfProtection` is on and `server.enableCORS` is off at the same time, we will prioritize `server.enableXsrfProtection`.
# Default: true
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
enableXsrfProtection = true

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
maxUploadSize = 1000000



# Enables support for websocket compression.
# Default: true
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
enableWebsocketCompression = true





[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
#base =

# Primary accent color for interactive elements.
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
primaryColor = "#de8ba1"

# Background color for the main content area.
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
backgroundColor = "#f4f1ea"

# Background color used for the sidebar and most interactive widgets.
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
secondaryBackgroundColor = "#9fe4cc"

# Color used for almost all text.
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
textColor = "#262730"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# The value below was set in /Users/tylerjrichards/.streamlit/config.toml
font = "sans serif"